eqp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('eqp/', views.eqp_home, name = 'eqp_home'),
]

manpower/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.mp_home, name = 'mp_home'),
    path('user_page/<str:pk>/', views.user_page, name = 'user_page'),
    path('mp_list/', views.mp_list, name = 'mp_list'),
    path('mp_search/', views.mp_search, name = 'mp_search'),
    path('mp_search_list/', views.mp_search_list, name = 'mp_search_list'),
    path('mplist', login_required(views.MpList.as_view()) , name = 'mplist'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('eqp/',  include("eqp.urls")),
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("manpower/", include("manpower.urls")),
    path("plan/", include("plan.urls")),
    path("report/", include("report.urls")),
    path("test/", include("tests.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

manpower/models.py
from django.db import models
from plan.models import Project
from simple_history.models import HistoricalRecords
from home.models import Department, Governorate


class Job_type(models.Model):
    title = models.CharField(max_length=50, primary_key=True)
    description = models.TextField(null=True, blank=True)
    def __str__(self):
      return self.title


class Title_list(models.Model):
    title = models.CharField(max_length=50, primary_key=True)
    description = models.TextField(null=True, blank=True)
    def __str__(self):
      return self.title


class Contract(models.Model):
   contract = models.CharField(max_length=50, primary_key=True)
   description = models.TextField(null=True, blank=True)
   def __str__(self):
      return self.contract

class Code(models.Model):
    mp_code = models.CharField(max_length=7, primary_key=True)
    title = models.ForeignKey(Title_list, on_delete=models.CASCADE) 
    job = models.CharField(max_length=50)
    speciality = models.CharField(max_length=50, default="عام")
    dep = models.ForeignKey(Department,on_delete=models.CASCADE)
    c_calc = [
        ('direct', 'direct'),
        ('indirect', 'indirect'),
    ]
    calc = models.CharField(max_length=10, choices=c_calc)
    job_type = models.ForeignKey(Job_type,on_delete=models.CASCADE)
    displayfields = ['mp_code','title','job', 'speciality','dep']
    search_fields = ['mp_code','title','job', 'speciality']
    list_filter = ['title','job', 'speciality']
    def __str__(self):
      return self.mp_code

def upload_path(instance, filename):
    return f'mp/users/{instance.id}/{filename}'

class Mp_list(models.Model):
  id = models.CharField(max_length=8, primary_key=True)
  first_name = models.CharField(max_length=20, null=False, blank=False)
  middle_name = models.CharField(max_length=20, null=False, blank=False)
  last_name = models.CharField(max_length=20, null=False, blank=False)
  full_name = models.CharField(max_length=100, null=True, blank=True)
  code = models.ForeignKey(Code,on_delete=models.CASCADE)
  full_discription = models.TextField(null=True, blank=True)
  hire = models.DateField(auto_now=False, auto_now_add=False)
  birth = models.DateField(auto_now=False, auto_now_add=False)
  gender_choices = [
        ('male', 'male'),
        ('female', 'female'),
  ]
  gender = models.CharField(max_length=10, choices=gender_choices)
  contract = models.ForeignKey(Contract,on_delete=models.CASCADE)
  gov = models.ForeignKey(Governorate,on_delete=models.CASCADE)
  national_id = models.BigIntegerField()
  photo = models.ImageField(upload_to=upload_path, default="static\images\default\worker.jpg")
  created = models.DateTimeField(auto_now_add=True) 
  update = models.DateTimeField(auto_now=True)
  history = HistoricalRecords()
  displayfields = ['id','first_name','last_name']
  search_fields = ['id','first_name','last_name']
  list_filter = []
  class Meta:
    ordering = ['id']
    indexes = [
    models.Index(fields=['id']),
    models.Index(fields=['first_name']),
    models.Index(fields=['last_name']),
    ]
  def __str__(self):
      return f"{self.id} | {self.first_name}  {self.last_name}"

class Mp_Location(models.Model):
    id = models.CharField(max_length=8, primary_key=True)
    recipient = models.ForeignKey( Project, on_delete=models.CASCADE)
    history = HistoricalRecords()
    def __str__(self):
      return f"{self.id} | {self.recipient}"

manpower/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Mp_Location, Mp_list


class Mp_move(forms.ModelForm):
  class Meta:
    model = Mp_Location
    fields = ['id','recipient']



class Mp_search(forms.ModelForm):
  class Meta:
    model = Mp_list
    fields = ["id","full_name","code","gender","contract","gov","national_id"]



   

manpower/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .models import Mp_list
from .forms import Mp_move, Mp_search
from .filters import Mp_list_Filter
# from django.db import IntegrityError
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
# from django.db.models.query import QuerySet
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.core.cache import cache
from django.db.models import Q


@login_required()
def mp_home(request):
  return render(request, 'manpower/mp_home.html')


@login_required()
def user_page(request,pk):
  target_user = Mp_list.objects.get(id = pk)
  context = {"target_user": target_user}
  return render(request, "manpower/user_page.html", context)


class MpList(ListView):
  model = Mp_list
  def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
    context = super().get_context_data(**kwargs)
    counter = Mp_list.objects.count()
    context['counter'] = counter
    return context
  # def get_queryset(self,filter) -> QuerySet[Any]:
  #   return Mp_list.objects.filter(title = filter)
  ordering = ["-id"]
  paginate_by = 200

# -------------------- جدول بيانات العمال
@login_required()
def mp_list(request):
  mp_list = Mp_list.objects.all()
  mp_list_filter = Mp_list_Filter(request.GET, queryset= mp_list)
  mp_list = mp_list_filter.qs
  page = request.GET.get('page', 1)
  paginator = Paginator(mp_list_filter.qs, 50)
  try:
    mp_list = paginator.page(page)
  except PageNotAnInteger:
    mp_list = paginator.page(1)
  except EmptyPage:
    mp_list = paginator.page(paginator.num_pages) 
  context = {
     "mp_list": mp_list,
     "filter": mp_list_filter,
              }
  return render(request, 'manpower/mp_list.html',context )
# --------------------


@login_required()
def mp_search(request):
  mp_list = Mp_list.objects.all()
  filter = Mp_list_Filter(request.GET, queryset=mp_list)
  mp_list = filter.qs
  context = {"filter": filter}
  return render(request, 'manpower/mp_search.html',context )

@login_required()
def mp_search_list(request):
  mp_list = Mp_list.objects.all()
  filter = Mp_list_Filter(request.GET, queryset=mp_list)
  mp_list = filter.qs
  context = {"mp_list": mp_list}
  return render(request, 'manpower/mp_list.html',context )





@login_required()
def error(request):
  return render(request, 'manpower/error.html')


@login_required()
def something_went_wrong(request):
  return render(request, 'manpower/something_went_wrong.html')


@login_required()
def created(request):
  return render(request, 'manpower/created.html')

templates/manpower/created.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetroJet</title>
    <link rel="icon" type="image/x-icon" href='{% static "images/logo.png" %}'>
</head>
<body>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <div class="wrappermax">
        <a href="/">
        <div class="logo">
            <img src='{% static "images/logo.png" %}' alt="PetroJet Logo">
        </div>
        </a>
        <div class="text-center mt-4 name">
            PetroJet
        </div>
        <hr>
        <h3 class="alert alert-success text-center">تم الاضافة الى قرارات النقل
            <br>
            <br>
            <a dir="auto" style="text-decoration: none" class="mt-3" href="{% url 'mp_move' %}"><strong>اصدار قرار نقل جديد</strong></a>
            <hr>
            <a style="text-decoration: none" href="{% url 'mp_home' %}">Back to home</a>
        </h3>
        <hr>
        

    </div>
</body>
</html>
{% endblock content %}

templates/manpower/error.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetroJet SignUp</title>
    <link rel="icon" type="image/x-icon" href='{% static "images/logo.png" %}'>
</head>
<body>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <div class="wrappermax">
        <a href="/">
        <div class="logo">
            <img src='{% static "images/logo.png" %}' alt="PetroJet Logo">
        </div>
        </a>
        <div class="text-center mt-4 name">
            PetroJet
        </div>
        <hr>
        <h3 class="alert alert-danger text-center">Employee Id does not exist
            <br>
            <a style="text-decoration: none" href="mailto:Hossam.dm@outlook.com">contact the admin</a>
        </h3>
        <hr>
        

    </div>
</body>
</html>
{% endblock content %}

templates/manpower/mp_history_list.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class = "container card br mt-4 d-flex overflow-x-auto">
    <div class = "p-3">
        <!-- head s-->
        <h1 class="text-center bold mt-3 mb-0">
        بيان عدم التنفيذ
        </h1>
        <h3 class="text-center bold">يظهر بيانات العمال اللتى تم عمل قرار نقل لهم ولم يتم التنفيذ</h3>
        <!-- head f-->
        <table class="table table-responsive" 
            id = "dt"
        >
            <thead>
                <tr>
                    <th>#</th>
                    <th>transaction</th>
                    <th>id</th>
                    <th>Recipient</th>
                    <th>date</th>
                </tr>
            </thead>
            <tbody>
                {% for row in mp_history_list %}
                    {% with counter=forloop.counter %}
                    <tr class="dh fs-5">
                        <td><div>{{ counter }}</div></td>
                        <td>{{row.transaction}}</td>
                        <td>{{row.id}}</td>
                        <td>{{row.recipient}}</td>
                        <td>{{row.date}}</td>
                    </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock  %}

templates/manpower/mp_home.html
{% extends "index.html" %}
{% block content %}

<div class="container br d-flex card mt-4 p-4">
  <h1 class="text-center bold mt-3 mb-0">
    منظومة الموارد البشرية للفرع الشرقى
  </h1>
  <hr />
  <div class="row justify-content-evenly">
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">بيانات العاملين</h3>
        </div>
        <!-- ------------ -->
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Employee Information
        </button>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 dir="rtl" class="modal-title fs-5" id="exampleModalLabel">انت تحاول الوصول الى نتائج مشفرة</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body"><strong class="">
                يتم استخدام نظام تشفير لحماية بيانات العاملين <br>
                هذا قد يؤدى الى تاخر ظهور بعض النتائج <br>
                ينصح باستخدام البحث
              </strong>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url  'mp_search' %}" class="btn btn-success">
                  استخدام البحث
                </a>
                <a href="{% url  'mp_list' %}" class="btn btn-danger">
                  Open database {NOT Recommended}
                </a>
              </div>
            </div>
          </div>
        </div>
        <!-- ----------- -->
      </div>
    </div>
    <!-- ---------- -->
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">اصدار قرار نقل</h3>
        </div>
        <a 
        href="{% url  'manpower_test_move' %}"
        class="btn btn-primary"
          >Project Assignment</a
        >
      </div>
    </div>
    <!-- ---------- -->
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">قرارات النقل</h3>
        </div>
        <a
        href="{% url  'mp_move_list' %}"
        class="btn btn-primary"
          >Assignment List</a
        >
      </div>
    </div>
    <!-- ---------- -->
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">توزيع العاملين</h3>
        </div>
        <a 
        {% comment %} href="#"  {% endcomment %}
        class="btn btn-primary disabled"
          >Job Position and Role</a
        >
      </div>
    </div>
    <!-- ---------- -->
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">جدول الاجازات</h3>
        </div>
        <a 
        {% comment %} href="#"  {% endcomment %}
        class="btn btn-primary disabled"
          >Schedule Management</a
        >
      </div>
    </div>
    <!-- ---------- -->
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">حساب الكفاءة للعامل</h3>
        </div>
        <a 
        {% comment %} href="#"  {% endcomment %}
        class="btn btn-primary disabled"
          >KPI Management</a
        >
      </div>
    </div>
    <!-- ---------- -->
    <div class="card text-center br m-2" style="width: 18rem">
      <div class="card-body">
        <div dir="rtl" class="">
          <h3 class="card-title">سجل تدريب العاملين</h3>
        </div>
        <a 
        {% comment %} href="#"  {% endcomment %}
        class="btn btn-primary disabled"
          >Training</a
        >
      </div>
    </div>
    
  </div>
</div>

{% endblock %}

templates/manpower/mp_list.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
<div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Active Control</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
        <form method = "get" action="{% url 'mp_search_list' %}">
            {% csrf_token %}
            {{filter.form|crispy}}
        <button type="submit" class="btn btn-succress">Filter</button>
        </form>
    </div>
</div>
</div>

<div class = "container card br mt-4 d-flex overflow-x-auto">
        <!-- head s-->
        <h1 class="text-center bold mt-3 mb-0">
            قائمة العاملين بالشركة
          </h1>
          <hr>
          <h6 class="text-center bold">استخدم الفلتر لاظهار نتائج اكثر دقة</h6>
          <h6 class="text-center bold">اضغط على الرقم المالى لاظهار بيانات العامل</h6>
          <!-- head f-->
    <div class = "p-3">
        <div class="d-flex flex-row-reverse mb-2">
            <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Filter
            </a>
        </div>
        <table class="table table-responsive" 
            id = "dt"
        >
            <thead>
                <tr>
                    <th>#</th>
                    <th>id</th>
                    <th>Name</th>
                    <th>contract</th>
                    <th>Title</th>
                    <th>Actual Job</th>
                    <th>speciality</th>
                    <th>department</th>
                </tr>
            </thead>
            <tbody>
                {% for row in mp_list %}
                    {% with counter=forloop.counter %}
                    <tr class="dh fs-5">
                        <td><div>{{ counter }}</div></td>
                        <td><a href="{% url  'user_page' row.id %}"><div>{{ row.id }}</div></a></td>
                        <td><strong>{{ row.first_name }} {{ row.middle_name }} {{ row.last_name }}</strong></td>
                        <td>{{row.contract}}</td>
                        <td>{{row.code.title}}</td>
                        <td>{{row.code.job}}</td>
                        <td>{{row.code.speciality}}</td>
                        <td>{{row.code.dep}}</td>
                    </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        <!-- Pagenation -->
        {% if mp_list.has_other_pages  %}
        <nav aria-label="Page navigation example w-50 d-flex justify-content-between mt-3">
            <ul class="pagination justify-content-center flex-wrap">
                {% if mp_list.has_previous  %}                  
                <li class="page-item mt-1">
                    <a class="page-link" href="?page={{mp_list.previous_page_number}}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled mt-1">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}

                {% for i in mp_list.paginator.page_range %}
                <li class="page-item mt-1"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                {% endfor %}
                
                {% if mp_list.has_next  %}  
                <li class="page-item mt-1">
                    <a class="page-link" href="?page={{mp_list.next_page_number}}">Next</a>
                </li>
                {% endif %}
            </ul>
          </nav>
          {% endif %}
        <!-- --------- -->
    </div>
</div>
{% endblock  %}

templates/manpower/mp_list_list.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
<div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Active Control</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
    <form method = "get">
        <hr>
        {{object_filter.form|crispy}}
        <hr>
    <button type="submit" class="btn btn-primary fs-5 fw-semibold">Submit</button>
    </form>
    </div>
</div>
</div>

<div class = "container card br mt-4 d-flex overflow-x-auto">
    <div class = "p-3">
        <div class="d-flex flex-row-reverse mb-2">
            <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Filter
            </a>
        </div>
        <hr>
        <h3>{{counter}}</h3>
        <table class="table table-responsive" 
            id = "dt"
        >
            <thead>
                <tr>
                    <th>#</th>
                    <th>id</th>
                    <th>Name</th>
                    <th>contract</th>
                    <th>Title</th>
                    <th>Actual Job</th>
                    <th>speciality</th>
                    <th>department</th>
                </tr>
            </thead>
            <tbody>
                {% for row in mp_list_list %}
                    {% with counter=forloop.counter %}
                    <tr class="dh fs-5">
                        <td><div>{{ counter }}</div></td>
                        <td><a href="{% url  'user_page' row.id %}"><div>{{ row.id }}</div></a></td>
                        <td><strong>{{ row.first_name }} {{ row.middle_name }} {{ row.last_name }}</strong></td>
                        <td>{{row.contract}}</td>
                        <td>{{row.code.title}}</td>
                        <td>{{row.code.job}}</td>
                        <td>{{row.code.speciality}}</td>
                        <td>{{row.code.dep}}</td>
                    </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock  %}

templates/manpower/mp_move.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<div class="wrappermax">
    <a href="/">
        <div class="logo">
            <img src='{% static "images/main/logo.png" %}' alt="PetroJet Logo">
        </div>
        </a>
    <div class="text-center mt-4 name">
        PetroJet
        <h2>نقل عامل</h2>
        <h4>قم بادخال الرقم المالى وتحديد المشروع المطلوب النقل اليه</h4>
    </div>
    <form method = "post">
        <hr>
        {% csrf_token %}
        {{form|crispy}}
        <hr>
    <button type="submit" class="btn fs-5 fw-semibold">Submit</button>
    </form>
</div>
{% endblock content %}

templates/manpower/mp_move_list.html
{% extends "index.html" %}
{% block content %}

<div class = "container card br mt-4 d-flex overflow-x-auto text-center">
    <h1 class="pt-3">بيان عدم التنفيذ</h1>
    <div class = "p-3">
        <div class="d-flex flex-row-reverse mb-2">
            <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Filter
            </a>
        </div>
        <table class="table table-responsive" 
            id = "datatable"
        >
            <thead>
                <tr>
                    <th>#</th>
                    <th>id</th>
                    <th>Name</th>
                    <th>contract</th>
                    <th>Title</th>
                    <th>Actual Job</th>
                    <th>speciality</th>
                    <th>department</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="container text-center card br mt-4 d-flex overflow-x-auto">

        <div class = "p-3">
            <table class="table table-responsive" 
            id = "datatable"
            >
                <thead>
                    <tr>
                        <th>transaction</th>
                        <th>id</th>
                        <th>recipient</th>
                        <th>date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in list%}
                        {% with counter=forloop.counter %}
                        <tr class="dh fs-5">
                            <td><div>{{ counter }}</div></td>
                            <td><a href="{% url  'user_page' row.id %}"><div>{{ row.id }}</div></a></td>
                        </tr>
                        {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
</div>



{% endblock  %}

templates/manpower/mp_search.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<div class="wrappermax">
    <a href="/">
        <div class="logo">
            <img src='{% static "images/main/logo.png" %}' alt="PetroJet Logo">
        </div>
        </a>
    <div class="text-center mt-4 name">
        PetroJet
  </div>
  <form method="get" action="{% url 'mp_search_list' %}">
    {% csrf_token %} {{filter.form|crispy}}
    <button type="submit" class="btn">Search</button>
  </form>
</div>
{% endblock content %}

templates/manpower/something_went_wrong.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetroJet SignUp</title>
    <link rel="icon" type="image/x-icon" href='{% static "images/logo.png" %}'>
</head>
<body>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <div class="wrappermax">
        <a href="/">
        <div class="logo">
            <img src='{% static "images/logo.png" %}' alt="PetroJet Logo">
        </div>
        </a>
        <div class="text-center mt-4 name">
            PetroJet
        </div>
        <hr>
        <h3 class="alert alert-danger text-center">Something went wrong
            <br>
            <a style="text-decoration: none" href="mailto:Hossam.dm@outlook.com">contact the admin</a>
        </h3>
        <hr>
        

    </div>
</body>
</html>
{% endblock content %}